version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/travis/build/
    overwrite: yes

hooks:
  AfterInstall:
    - location: /home/ec2-user/app/travis/deploy.sh
      timeout: 120
      runas: ec2-user

